name: Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  review-warnings-and-build:
    name: "Source files are prettified, then verify if build is possible"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out Code
        uses: actions/checkout@v5

      - name: Read .nvmrc
        id: node_version
        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install Dependencies
        continue-on-error: false
        run: |
          corepack enable
          yarn install

      - name: Check if build is correct
        continue-on-error: false
        run: |
          yarn build

      - name: Check if Files are Prettified
        continue-on-error: false
        run: |
          ./check-prettier.sh
